# Generated by Django 3.0.4 on 2020-04-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='profilePic',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
