# Generated by Django 3.0.4 on 2020-04-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('qtext', models.CharField(max_length=1000)),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
                ('rtoption', models.CharField(max_length=200)),
            ],
        ),
    ]
