# Generated by Django 3.0.4 on 2020-04-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pid',
            new_name='paperID',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='tag',
            new_name='questionTag',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='qtext',
            new_name='questionText',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='rtoption',
            new_name='rightOption',
        ),
    ]
