# Generated by Django 3.0.4 on 2020-04-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200423_1014'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('paperID', 'questionText')},
        ),
    ]
