# Generated by Django 3.0.4 on 2020-04-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200423_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='studyMaterial',
            fields=[
                ('materialID', models.AutoField(primary_key=True, serialize=False)),
                ('materialTag', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('materialFile', models.FileField(upload_to='')),
            ],
        ),
    ]
