# Generated by Django 3.0.4 on 2020-04-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20200428_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profilePic',
        ),
    ]
