# Generated by Django 3.0.4 on 2020-04-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_student_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='paperTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperID', models.CharField(max_length=100)),
                ('quizTime', models.IntegerField(default=60)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='questionMarks',
            field=models.IntegerField(default=4),
        ),
    ]
