# Generated by Django 3.0.4 on 2020-04-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20200429_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='liveQuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperID', models.CharField(max_length=100)),
                ('paperDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='liveTestPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.EmailField(max_length=254)),
                ('paperID', models.CharField(max_length=100)),
                ('studentMarks', models.IntegerField()),
            ],
        ),
    ]
