# Generated by Django 3.0.4 on 2020-04-30 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_livequestionpaper_livetestperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='livequestionpaper',
            name='quizTime',
            field=models.TimeField(default=datetime.time(11, 5, 16, 256103)),
        ),
        migrations.AlterField(
            model_name='livequestionpaper',
            name='paperDate',
            field=models.DateField(),
        ),
    ]
