# Generated by Django 3.0.4 on 2020-04-30 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20200430_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livequestionpaper',
            name='paperDate',
            field=models.DateField(default=datetime.date(2020, 4, 30)),
        ),
        migrations.AlterField(
            model_name='livequestionpaper',
            name='quizTime',
            field=models.TimeField(default=datetime.time(11, 5, 49, 19751)),
        ),
    ]
