# Generated by Django 3.0.4 on 2020-04-30 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20200430_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livequestionpaper',
            name='paperDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='livequestionpaper',
            name='quizTime',
            field=models.TimeField(default=datetime.time(11, 6, 37, 77324)),
        ),
    ]
