# Generated by Django 3.0.4 on 2020-04-30 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20200430_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livequestionpaper',
            name='id',
        ),
        migrations.AlterField(
            model_name='livequestionpaper',
            name='paperID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='livequestionpaper',
            name='quizTime',
            field=models.TimeField(default=datetime.time(11, 15, 38, 159666)),
        ),
    ]
