# Generated by Django 3.0.4 on 2020-04-30 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20200430_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papertime',
            name='id',
        ),
        migrations.AlterField(
            model_name='livequestionpaper',
            name='quizTime',
            field=models.TimeField(default=datetime.time(11, 18, 47, 559019)),
        ),
        migrations.AlterField(
            model_name='papertime',
            name='paperID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
