# Generated by Django 3.0.4 on 2020-04-30 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20200430_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livequestionpaper',
            name='quizTime',
            field=models.TimeField(default=datetime.time(16, 26, 44, 965013)),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
