# Generated by Django 3.0.4 on 2020-05-01 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20200430_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livequestionpaper',
            name='quizTime',
            field=models.TimeField(default=datetime.time(13, 39, 15, 333374)),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionText',
            field=models.TextField(),
        ),
    ]
