# Generated by Django 3.0.4 on 2020-05-01 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20200501_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livequestionpaper',
            name='quizTime',
            field=models.TimeField(default=datetime.time(13, 44, 12, 395767)),
        ),
    ]
