# Generated by Django 3.0.4 on 2020-05-01 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_auto_20200501_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profilePic',
        ),
        migrations.AlterField(
            model_name='livequestionpaper',
            name='quizTime',
            field=models.TimeField(default=datetime.time(13, 45, 51, 807838)),
        ),
    ]
