# Generated by Django 3.0.4 on 2020-05-01 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_auto_20200501_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profilePic',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='livequestionpaper',
            name='quizTime',
            field=models.TimeField(default=datetime.time(13, 47, 4, 142513)),
        ),
    ]
