# Generated by Django 3.0.4 on 2020-05-01 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_auto_20200501_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='livequestionpaper',
            name='quizTime',
            field=models.TimeField(default=datetime.time(14, 34, 3, 441141)),
        ),
    ]
